using System.Collections.Generic;
using UnityEngine;

namespace MiniGame.PenguinWars.Art
{
    public static partial class PenguinPartPatterns
    {
        /// <summary>
        /// 手に持つパーツ。Anchor はパターン内で体の目印 A（手）に重ねる位置。攻撃のコマでは持ち物ごとずれるので、
        /// 振って見せたいもの（武器）は手より上へ伸ばす
        /// </summary>
        public static readonly Dictionary<string, PartPattern> Hands = new Dictionary<string, PartPattern>
        {
            ["axe"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(2, 11), new[]
            {
                "..ooooo...",
                ".obsssso..",
                ".obssssso.",
                ".obmsssso.",
                ".obmmmoo..",
                ".obo......",
                ".obo......",
                ".obo......",
                ".obo......",
                ".obo......",
                "okkko.....",
                "okkko.....",
                ".ooo......",
            }),
            ["glove"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(1, 3), new[]
            {
                "..oooo..",
                ".ottttoo",
                "okttttto",
                "okttttuo",
                "okkuuuuo",
                ".ooooo..",
            }),
            ["bow"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(2, 7), new[]
            {
                ".oo.......",
                ".nboo.....",
                ".n.bbo....",
                ".n..bo....",
                ".n...bo...",
                ".n...bo...",
                ".n...bo...",
                ".ndddbddso",
                ".n...bo...",
                ".n...bo...",
                ".n...bo...",
                ".n..bo....",
                ".n.bbo....",
                ".nboo.....",
                ".oo.......",
            }),
            ["big_snowball"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(3, 4), new[]
            {
                "..ooooo..",
                ".owwwwwo.",
                "owwwwwwlo",
                "owwwwwwlo",
                "owwwwwwlo",
                "owwwwwllo",
                "owwwwllio",
                ".olllllo.",
                "..ooooo..",
            }),
            // 頭の上まで振りかぶった雪玉（抱えるだけの「ゆきだま」と見分けるため）
            ["snowball_throw"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(2, 10), new[]
            {
                ".ooo.",
                "owwlo",
                "owwlo",
                "oolo.",
                ".oko.",
                ".oko.",
                ".oko.",
                ".oko.",
                ".oko.",
                "okko.",
                "okkko",
                ".ooo.",
            }),
            ["fish_sword"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(2, 13), new[]
            {
                "..oo...",
                ".olio..",
                "oleiio.",
                "olllio.",
                "olllio.",
                "olllio.",
                "olllio.",
                "olllio.",
                ".olio..",
                "..oo...",
                ".olio..",
                "oliiio.",
                ".okko..",
                ".okko..",
                "..oo...",
            }),
            ["hammer"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(5, 12), new[]
            {
                "oooooooooooo",
                "osssssssssmo",
                "osssssssssmo",
                "osssssssssmo",
                "osssssssssmo",
                "ommmmmmmmmmo",
                "oooooobboooo",
                ".....obbo...",
                ".....obbo...",
                ".....obbo...",
                ".....obbo...",
                ".....okko...",
                ".....okko...",
                ".....oooo...",
            }),
            ["katana"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(2, 13), new[]
            {
                "..o..",
                ".oso.",
                ".oso.",
                ".oso.",
                ".oso.",
                ".oso.",
                ".oso.",
                ".oso.",
                ".oso.",
                ".oso.",
                ".oso.",
                "ogggo",
                ".ono.",
                ".ono.",
                ".ooo.",
            }),
            // 剣と盾を1パーツにする（手の目印は1つなので）。盾はお腹の前、剣は上へ
            ["sword_shield"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(9, 9), new[]
            {
                ".........o..",
                "........oso.",
                "........oso.",
                "........oso.",
                "........oso.",
                "........oso.",
                "........oso.",
                ".......ogggo",
                "ooooooo.ono.",
                "ottgtto.ono.",
                "ottgtto.ooo.",
                "ogggggo.....",
                "ottgtto.....",
                "ottgtto.....",
                ".ottto......",
                "..oto.......",
                "...o........",
            }),
            // 力こぶを作った太い腕
            ["muscle_arm"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(4, 10), new[]
            {
                "...ooo...",
                "..okkko..",
                ".okkkkko.",
                ".okkkkko.",
                "okkkkkkko",
                "okkkkkkko",
                "okkkkkko.",
                ".okkkko..",
                "..okkko..",
                "..okkko..",
                "..okkko..",
                "...ooo...",
            }),
            // 釣り竿の先から糸を垂らし、先に魚が掛かっている
            ["fishing_rod"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(1, 13), new[]
            {
                "...........dd.",
                "..........d.w.",
                ".........d..w.",
                "........d...w.",
                ".......d....w.",
                "......d.....w.",
                ".....d.....oo.",
                "....d.....olio",
                "...d......olio",
                "..d.......oiio",
                ".dd........oo.",
                "dnd.......oio.",
                "dd............",
                "dd............",
            }),
            // 肩に担いだ大砲。砲口を前に向け、手で下から支える
            ["cannon"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(7, 6), new[]
            {
                "...............ooooo",
                "oooooooooooooooomnno",
                "ommmgmmmmmmmmmmmmnno",
                "osssgsssssssssssmnno",
                "ommmgmmmmmmmmmmmmnno",
                "oooooooooooooooomnno",
                "......okko.....ooooo",
                "......okko..........",
                "......oooo..........",
            }),
            ["staff"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(2, 12), new[]
            {
                "..o..",
                ".opo.",
                "oppwo",
                ".opo.",
                "..o..",
                ".obo.",
                ".obo.",
                ".obo.",
                ".obo.",
                ".obo.",
                ".obo.",
                ".obo.",
                ".obo.",
                ".obo.",
                ".ooo.",
            }),
            // 体より長い銃を水平に構える（射程最長クラスと分かるように）
            ["sniper_rifle"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(11, 5), new[]
            {
                "..........oooooo........",
                "..........onnnno........",
                "oooooooooooooooooooooooo",
                "obbbbbbbmmmmmmmmmmmmmmmo",
                "obbbbbbboooooooooooooooo",
                "obbbbo....okko..........",
                "ooooo.....oooo..........",
            }),
            ["boomerang"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(2, 7), new[]
            {
                "oo........",
                "obo.......",
                "obdo......",
                "obdo......",
                "obdo......",
                "obbdo.....",
                "obbbdooooo",
                "obbbbbbbbo",
                "odddddddoo",
                "oooooooo..",
            }),
            // 扇風機。羽の前に風の線を出して「ふっとばす」と分かるようにする
            ["fan"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(4, 10), new[]
            {
                "..ooooo......",
                ".oslllso.....",
                "osllsllso.www",
                "olllmlllo....",
                "olsmmmslo.www",
                "olllmlllo....",
                "osllsllso.www",
                ".oslllso.....",
                "..ooooo......",
                "...omo.......",
                "...omo.......",
                "...omo.......",
                "..ommmo......",
                "..ooooo......",
            }),
            ["harisen"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(4, 10), new[]
            {
                "ooooooooo",
                "owswswswo",
                "owswswswo",
                ".owswswo.",
                ".owswswo.",
                "..owswo..",
                "..owswo..",
                "...owo...",
                "...oro...",
                "...oro...",
                "...oro...",
                "...ooo...",
            }),
            ["mic"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(2, 6), new[]
            {
                ".ooo.",
                "osmso",
                "omsmo",
                "osmso",
                ".ooo.",
                ".ono.",
                ".ono.",
                ".ooo.",
            }),
            // 糸を長くして風船を頭より上に浮かせる
            ["balloon"] = new PartPattern(PartAttach.Hand, PartLayer.Front, new Vector2Int(3, 20), new[]
            {
                "..ooo..",
                ".orrro.",
                "orwrrro",
                "orrrrro",
                "orrrrxo",
                ".orrxo.",
                "..oxo..",
                "...n...",
                "...n...",
                "....n..",
                "....n..",
                "...n...",
                "...n...",
                "....n..",
                "....n..",
                "...n...",
                "...n...",
                "....n..",
                "....n..",
                "...n...",
                "..ono..",
                "...o...",
            }),
        };
    }
}
